# full reference:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

Metrics/MethodLength:
  Max: 12
  CountComments: false  # count full line comments?

Layout/LineLength:
  Enabled: true
  Max: 85

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

# Metrics/AbcSize:
#   Max: 24
