#!/bin/bash

OS=$(uname)

# install vim plugins
cd ~/.vim/
./update_plugins.rb
cd

# install git-friendly
bash < <( curl https://raw.github.com/jamiew/git-friendly/master/install.sh)

if [ $OS = "Darwin" ]; then
  # do any mac-specific setup here

elsif [ $OS = "Linux" ]; then

  apt-get update
  packages="build-essential git-core curl openssh-server dkms git htop redis-server vim zsh"
  for package in $packages
  do
    apt-get install $package
  done
  apt-get clean

fi
