#!/bin/bash
# John Manoogian III * jm3 * 2013

script=`basename $0`

dot_home="$HOME/.dotfiles"
library="$HOME/Library"
black_hole="/tmp/"

if [ ! -d "$dot_home" ]; then
  echo "move the dotfiles repo to $dot_home first, please."
  exit 1
fi

cd

if [ -f .bash_profile ]; then
  # abomination
  mv .bash_profile .bash_profile.old
fi

dots=`ls -a $dot_home`
for dot in $dots
do
  # skip unrelated files
  if [ $dot = ".DS_Store" \
    -o $dot = $script \
    -o $dot = "README.md" \
    -o $dot = ".rvmrc.off" \
    -o $dot = "osx" \
    -o $dot = ".git" ]; then
    continue
  fi

  if [ ! -L $dot -a ! -d $dot ]; then
    echo moving existing $dot out of the way
    if [ -e $dot.old ]; then
      mv $dot.old `mktemp $black_hole/$dot.XXX`
    fi
    mv $dot $dot.old
    ln -s $dot_home/$dot $dot
  fi
done

# set up vim
cd ~/.vim/
update-vim-bundles
cd $dot_home

os=`uname`
if [ $os = "Darwin" ]; then

  function setup_iterm() {
    echo "iTerm configs linked"
    iterm_cfg="$library/Preferences/net.sourceforge.iTerm.plist"
    if [ -f "$iterm_cfg" -a ! -L "$iterm_cfg" ]; then
      mv $iterm_cfg `mktemp $black_hole/net.sourceforge.iTerm.plist.XXX`
    fi
    if [ -L "$iterm_cfg" ]; then
      rm $iterm_cfg
    fi
    ln -s "$dot_home/osx/iterm/net.sourceforge.iTerm.plist" "$library/Preferences/net.sourceforge.iTerm.plist"
  }

  function setup_sublime_text() {

    # note that the HTML2Haml st plugin needs to be manuallly installed
    # from branch "SublimeText2" when running on ST2:
    #
    # cd $library/Application Support/SublimeText2/Packages/
    # git clone -b SublimeText2 https://github.com/pavelpachkovskij/sublime-html-to-haml.git "HTML2Haml"

    subl_home="$library/Application Support/Sublime Text 2/Packages/"

    if [ ! -d "$subl_home" ]; then
      echo "No Sublime Text package directory found (looked in $subl_home)"
      return
    fi

    cd "$subl_home"
    if [ "`readlink User`" = "$dot_home/osx/st" ]; then
      # if setup's been run before and we have a symlink to our configs, we're done
      echo "Sublime Text configs linked"
      return
    fi

    echo updating Sublime Text 2 configs
    if [ -f "old-configs.tgz" ]; then
      mv old-configs.tgz `mktemp $black_hole/old-configs.tgz.XXX`
    fi
    tar cvz User > old-configs.tgz &> /dev/null
    rm -rf User
    ln -s $dot_home/osx/st User
  }

  setup_iterm
  setup_sublime_text

# /osx
fi

exit 0
