source "http://rubygems.org"

gem "haml", "3.0.25"
gem "sinatra", "1.1.3"
gem "sinatra-bundles", "0.5.1"
gem "sinatra-content-for2", "0.2.4"
gem "tilt", "1.2.2"

gem "omniauth", "~> 1.1.0"
gem "omniauth-dropbox"
gem "omniauth-github"
gem "omniauth-twitter"

group :development do
  gem "debugger"
  gem "shotgun", "~> 0.9"
end

